[package]
name = "echoService"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "echoService"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.6.15"

[dev-dependencies]
marine-rs-sdk-test = "0.5.0"
